#!/usr/bin/env bash

ENVFILE=${1-.env}
[ -f "$ENVFILE" ] && source "$ENVFILE"

drop()
{
    echo [*] dropdb -U $POSTGRES_DATABASE_USER -h $POSTGRES_MASTER_SERVICE_HOST -p $POSTGRES_MASTER_SERVICE_PORT --if-exists $POSTGRES_DATABASE_NAME
    dropdb -U $POSTGRES_DATABASE_USER -h $POSTGRES_MASTER_SERVICE_HOST -p $POSTGRES_MASTER_SERVICE_PORT --if-exists $POSTGRES_DATABASE_NAME
}

create()
{
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    SCHEMA="$DIR/support/database/schema.sql"
    echo [*] createdb -U $POSTGRES_DATABASE_USER -h $POSTGRES_MASTER_SERVICE_HOST -p $POSTGRES_MASTER_SERVICE_PORT $POSTGRES_DATABASE_NAME
    createdb -U $POSTGRES_DATABASE_USER -h $POSTGRES_MASTER_SERVICE_HOST -p $POSTGRES_MASTER_SERVICE_PORT $POSTGRES_DATABASE_NAME
    POSTGRES_MASTER_SERVICE_HOST=$POSTGRES_MASTER_SERVICE_HOST \
        POSTGRES_MASTER_SERVICE_PORT=$POSTGRES_MASTER_SERVICE_PORT \
        POSTGRES_DATABASE_USER=$POSTGRES_DATABASE_USER \
        POSTGRES_DATABASE_PASSWORD=$POSTGRES_DATABASE_PASSWORD\
        POSTGRES_DATABASE_NAME=$POSTGRES_DATABASE_NAME farnsworth create
}

case "$1" in
    drop)
        drop
        ;;
    create)
        create
        ;;
    *)
        drop
        create
        ;;
esac
