<!-- -*- mode: markdown -*- -->
# Group API Status

## Ping [/ping]

### Ping [GET]

Ping endpoint can be used to check if the API is reachable.

+ Response 200 (application/json)

        {
            "status": "pong"
        }
